spring.application.name=MDSERP

spring.datasource.jdbcUrl=jdbc:sqlserver://186.28.243.188\\sqlfactory:63138;encrypt=false
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=MDS1610solPRO
#second data source Solid Works PDM
spring.second-datasource.jdbcUrl = jdbc:sqlserver://192.168.1.215\\mdsswpdmpro;encrypt=false
spring.second-datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.second-datasource.username = sa
spring.second-datasource.password = MD$2017PDMPRO


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
