spring.application.name=MDSERP

spring.datasource.jdbcUrl=jdbc:sqlserver://186.28.243.188\\sqlfactory:63138;encrypt=false
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#user for Back-end apps connection with read and write permissions to MDSERP database
spring.datasource.username=Back
spring.datasource.password=MDS1960solPRO
#second data source Solid Works PDM
spring.second-datasource.jdbcUrl = jdbc:sqlserver://186.28.243.189\\mdsswpdmpro:63139;encrypt=false
spring.second-datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#user for Back-end apps connection with read and write permissions to Solid Works PDM database
spring.second-datasource.username = Back
spring.second-datasource.password = MD$1960PDMPRO


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
